### ISSUE TITLE
Include Jackett as official plugin

### ISSUE THREAD

**Issue by ngosang** [hannsen/qbittorrent_search_plugins#12]
@hannsen 
Hi, I'm the official maintainer of qbittorrent plugins.
I want to promote this plugin to official. If you are interested:

1. Open a PR here https://github.com/qbittorrent/search-plugins
2. Modify the code to create "sample configuration file" if `jackett.json` doesn't exists.
3. Copy the same code to folders `nova` and `nova3`
4. Add it to files `nova/versions.txt` and `nova3/versions.txt`

I will review and merge the code asap.
Thank you

**Comment by hannsen** [comment]
go ahead 👍
