### ISSUE TITLE
MagnetDL plugin not working

### ISSUE THREAD

**Issue by gumpster2010** [hannsen/qbittorrent_search_plugins#14]
Hello hannsen --

I have been trying to use qBittorrent search and have noticed that one of your plugins, for MagnetDL, doesn't seem to be producing any results (even for searches that I know have results listed online). 

I am running qBittorrent 4.1.0.  I was running 4.1.3 but I noticed many plugins seemed incompatible with that one, so I returned to a prior version (which should be working according to the Unofficial search plugins list).  I also briefly tried 4.0.3 since I noticed MagnetDL was only supposed to work with 4.0.x versions, but it didn't seem to work for that version either.

Please let me know if I'm onto something or if it's more likely a problem with my install. 

Thanks!
Ian

**Comment by hannsen** [comment]
moved here https://github.com/nindogo/qbtSearchScripts/issues/6
