### ISSUE TITLE
Jackett & qBittorrent working fine, just not with each other (similar to issue #9 but not quite)

### ISSUE THREAD

**Issue by navjunk** [hannsen/qbittorrent_search_plugins#17]
Hi, 

My issue is similar to Issue #9 (https://github.com/hannsen/qbittorrent_search_plugins/issues/9) but environment is different. I have set it up on Linux Mint 20 (with Mono) and following are the details of environment and the issue: 

1. qBittorrent 4.3.3 is working fine with rest of the search plugins i.e. minus jackett  
2. installed jackett at /opt/Jackett and it is working fine as a service and accessible at http://localhost:9117/. I am able to perform manual searches with refined indexes and able to download both magnet and regular torrent sourced from it using qBittorrent.
3. For qBittorrent, the jackett.json file is also at the path specified for Mint 20.x, which is different than location for Mint previous versions. 

However in qBittorrent, jackett itself is not listed as a search plugin and jackett searches still do not work/ appear in the search section. I tried various things and reached this (Issue #9) post yesterday. Now, following is what I have tried myself and as per the post and where I stand:

1. From the installation and configuring instructions for Jackett, I saw that Jackett is enabled by default and can be disabled. While true for windows environment, I could not find the jackett appearing in search section/ plugins.
2. As per this post I realized there is supposed to be a jackett.py file, much like other search plugin .py files BUT jackett.py did not exist in my fresh installation in the nova3 or any directory where qBittorrent is installed. I understand the same is removed as a separate file and made standard with qBittorrent but as explained in previous point, it is not working for me in my environment. 
3. Following the project files, I downloaded the jackett.py file (i think this is standard non-debug version) in the nova3 directory but running 'python3 jackett.py' there gave the following error:

> http://127.0.0.1:9117|Failure to connect to Jackett server! Please check API Key and URL / harry potter|-1|-1|-1|http://127.0.0.1:9117|http://127.0.0.1:9117

4. But, I was sure that myy jason file was update though one directory deeper under engines, so I moved the jackett.py to engines folder and re-ran the command, this time I got

> Traceback (most recent call last):
>   File "jackett.py", line 19, in <module>
>     from novaprinter import prettyPrinter
> ModuleNotFoundError: No module named 'novaprinter' 

5. Again, I had seen the novaprinter.py in the previous directory nova3, so I moved both the jackett.py and jackett.json to nova3 and re-ran the command, this is what I got:

> Traceback (most recent call last):
>   File "jackett.py", line 129, in <module>
>     s.search("masked value", 'masked value')
>   File "jackett.py", line 91, in search
>     desc_link=i['Comments'])
> KeyError: 'Comments'

This means that jackett.py has everything it needs - API from json and novaprinter.py as well and its down to the jackett.py code itself. Still not working though.

6. Installing jackett.py as "install pllugin from file" functionality does not work either. 

So, while they both Jackett and qBittorrent work individually, they are not working with each other. Please guide.

**Comment by hannsen** [comment]
I don't maintain that plugin anymore, it's now an official plugin. Maybe you trying to use an old version from me and not the official one?

Please put your issue here:
https://github.com/qbittorrent/search-plugins/issues

**Comment by navjunk** [comment]
Ok Thanks.
