### ISSUE TITLE
magnetdl and mkvcage parse only 1 page

### ISSUE THREAD

**Issue by hannsen** [hannsen/qbittorrent_search_plugins#2]

**Comment by Pireo** [comment]
@ArionMiles @dwilbanks

**Comment by Pireo** [comment]
Have you ever tried with http://www.mkvcage.com/ ? Seems to be the official domain, and it gives you the magnet link too unlike the .bid one.

**Comment by Pireo** [comment]
https://stackoverflow.com/questions/26497722/scrape-multiple-pages-with-beautifulsoup-and-python

**Comment by hannsen** [comment]
You can't use beautifulsoup in these plugins, since it is not standard. 

I know how to do this, but am just not motivated

**Comment by nindogo** [comment]
I have added the multiple pages to magnetdl.py [here](https://raw.githubusercontent.com/nindogo/qbtSearchScripts/master/magnetdl.py).

Please consider replacing it. MagnetDL only allows you to go to page 30 despite having more results so I have stopped it at page 30.

**Comment by nindogo** [comment]
Did some cleanup and looping of [mkvcage](https://raw.githubusercontent.com/nindogo/qbtSearchScripts/master/mkvcage.py). Please check it out.

**Comment by nindogo** [comment]
So I introduced a whole lot of lovely new bugs.

Debugging now.

**Comment by nindogo** [comment]
Should be better now.

**Comment by hannsen** [comment]
wanna maintain both? i have no interest in mkvcage and for magnetdl I use jackett

**Comment by nindogo** [comment]
I could for some time - I am still a newbie in python.
How good is jackett?

**Comment by hannsen** [comment]
Jackett is nice, has a lot of sites.

Btw I would limit the magnetdl to 5 pages or something on default, its a bit over the top to request like 50 pages imo.

If you want you can edit the Plugins wiki page and replace magnetdl and mkvcage with yours
