### ISSUE TITLE
Jackett Plugin

### ISSUE THREAD

**Issue by ukharley** [hannsen/qbittorrent_search_plugins#5]
I have no idea how to use Git so I posted this about 5 days ago at the official qBittorrent plugin repo. Seems no one pays much attention there. Maybe you can review/revise it then add it here. To use/test it you will have to install Jackett...  https://github.com/Jackett/Jackett
It works for me, though I have not run exhaustive tests so there will be bugs I'm sure.

``` #VERSION: 1.0
#AUTHORS: ukharley

from novaprinter import prettyPrinter
from helpers import retrieve_url, download_file
import json

try:
  # python2
  from urllib import urlencode, quote, unquote
except ImportError:
  # python3
  from urllib.parse import urlencode, quote, unquote

class jacket(object):
    """Generic provider for Torznab compatible api."""

    def __init__(self):
        pass

    name = 'Jacket(torznab)'
    url = 'http://127.0.0.1:9117' #default, change to yours
    api_key = '' # add your api key
    supported_categories = {'all'   : '',
                            'movies': '2000',
                            'tv'    : '5000',
                            'music' : '3000',
                            'books' : '8000'
                            }

    def search(self, what, cat='all'):
        cat = cat.lower()
        baseURL = "http://127.0.0.1:9117/api/v2.0/indexers/all/results?%s"
        what = unquote(what)
        category = self.supported_categories[cat]
        if category != '':
            params = urlencode({
            'apikey': self.api_key,
            'Query': what,
            'Category[]': category
        })
        else:
            params = urlencode({
                'apikey': self.api_key,
                'Query': what,
            })

        response = retrieve_url(baseURL % params)
        j = json.loads(response)
        for i in j['Results']:
            tbytes = float(i['Size'])
            size = "-1"

            if tbytes > 1024 * 1024 * 1024:
                size = "%.1f GB" % (tbytes / (1024 * 1024 * 1024))

            elif tbytes > 1024 * 1024:
                size = "%.1f MB" % (tbytes / (1024 * 1024))

            elif tbytes > 1024:
                size = "%.1f KB" % (tbytes / 1024)

            else:
                size = "%.1f B" % (tbytes)

            if i['MagnetUri']:
                res = dict(link=i['MagnetUri'],
                           name=i['Title'],
                           size=size,
                           seeds=i['Seeders'],
                           leech=i['Peers'],
                           engine_url=self.url,
                           desc_link = i['Comments'])
            else:
                res = dict(link=i['Link'],
                           name=i['Title'],
                           size=size,
                           seeds=i['Seeders'],
                           leech=i['Peers'],
                           engine_url=self.url,
                           desc_link=i['Comments'])

            prettyPrinter(res)

if __name__ == "__main__":
    s = jacket()
    s.search("harry potter", 'movies')
```

**Comment by hannsen** [comment]
Nice, i will review it. I doubt they will accept it in the official repository.

**Comment by hannsen** [comment]
^ I changed some code for ease of use, but the functionality stayed. I will put it in the search plugin list. Thx for this

**Comment by hannsen** [comment]
@ukharley I just found out you can get the api_key from this url 

http://127.0.0.1:9117/api/v2.0/server/config

So the user wouldn't have to paste his key in. Do you see any complications?

**Comment by ukharley** [comment]
No, If tested and it works makes it much easier for the user.

**Comment by ukharley** [comment]
A URL check of some sort would be handy as well. I'll have a play and see if I can come up with something.

**Comment by hannsen** [comment]
You mean guessing the jackett url?

**Comment by ukharley** [comment]
That's right yeah. I don't know if qBittorrent will allow a message saying wrong URL set for Jackett or something. I'm sure there must be something that can be done. I'll play with it tonight or tomorrow if I have some time. See if you can come up with something too.

**Comment by hannsen** [comment]
I did something like that here

https://github.com/hannsen/qbittorrent_search_plugins/blob/master/demonoid.py#L146

the search string needs to be in the results for qbit to show it

**Comment by ukharley** [comment]
I had a look at further automation but it doesn't work. qBittorrent fails
to load the plugin if the URL check fails so it's probably best to leave it
as is.

**Comment by hannsen** [comment]
I updated it to check for connection errors and the api key

**Comment by ukharley** [comment]
Well done. My coding skills are limited. I just mess about 'till i get
stuff working (or not lol.)

**Comment by hannsen** [comment]
Well at least your first one worked :D
