### ISSUE TITLE
 are you interested in cinecalidad.to and etrg-torrent.com since they're quite popular?

### ISSUE THREAD

**Issue by Pireo** [hannsen/qbittorrent_search_plugins#7]
https://www.facebook.com/cinecalidad/

https://www.alexa.com/siteinfo/cinecalidad.to

http://etrg-torrent.com/
etrg is legit unlike yts and eztv, has both tv shows and movies, and cinecalidad is the most popular spanish movie site.

**Comment by hannsen** [comment]
naw sorry
